version: "3.6"
services:
  proxy:
    image: avillalba96/docker-squidproxy:1.0
    container_name: 'proxy'
    hostname: proxy
    ports:
      - "3128:3128"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
    volumes:
      - ./squid/cache:/var/spool/squid
      - ./squid/conf:/etc/squid
      - ./squid/logs:/var/log/squid
    restart: unless-stopped
    environment:
      - TZ=America/Argentina/Buenos_Aires
